source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'bcrypt-ruby', '3.0.1'
gem 'jquery-rails', '2.0.2'
gem 'faker', '1.0.1'
gem 'bootstrap-will_paginate', '0.0.7'
gem 'simple_form', '~> 2.0.2'
gem 'rinku'

group :development do
  gem 'sqlite3', '1.3.6'
  gem 'rspec-rails', '2.10.1'
  gem 'annotate', ">=2.5.0.pre1"
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.5'
  gem 'bootstrap-sass', '2.0.3.1'
  gem 'font-awesome-sass-rails', '2.0.0.0'
end

# Test gems on Windows
group :test do
  gem 'rspec-rails', '2.10.1'
  gem 'capybara', '1.1.2'
  gem 'rb-fchange', '0.0.5'
  gem 'rb-notifu', '0.0.4'
  gem 'factory_girl_rails', '3.4.0'
  gem 'spork-rails', '3.2.0'
end 

group :production do
  gem 'pg', '0.13.2'
end