source "http://rubygems.org/"

gem 'sinatra'
gem 'data_mapper'
gem 'rack'
gem 'sinatra-redirect-with-flash'
gem 'rack-flash3'
gem 'json'
gem 'jsonify'
gem 'tilt'
gem 'rabl'
gem 'dm-types', '1.2.1'
gem 'builder'
gem 'activesupport', :require => ["active_support/core_ext","active_support/inflector"]


group :production do
  gem 'pg', '0.13.2'
  gem 'dm-postgres-adapter'
end
