# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4eec957512d4b10f78813c090a1570bba79ff891dd5bfd251b1560281ace3e9a1a858ffae926033bdf6678c0c8e4577209dfceee349a51d5476a674a31f33f6

test:
  secret_key_base: 9b40f595783c572a7ce2874dcc2b4710c770dcb0ea8cac724425098d8c9060acac6cf74e9431ed2eda33fdfecdca69897399626edbfafae11ca064b5ff29dfd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: a4eec957512d4b10f78813c090a1570bba79ff891dd5bfd251b1560281ace3e9a1a858ffae926033bdf6678c0c8e4577209dfceee349a51d5476a674a31f33f6

